### ISSUE TITLE
OLED.c

### ISSUE THREAD

**Issue by Dave-10** [gavinlyonsrepo/pic_16F1619_projects#1]
I found that Oled_Clear(); was not clearing the whole OLED unless Oled_SelectPage(0) was done first.
Maybe good to put Oled_SelectPage(0); inside the Oled_Clear(); function.

**Comment by gavinlyonsrepo** [comment]
Hi 

Done. 
FYI This is a minimalist light weight version of library. I have another version of this library with more fonts and graphics. Here ::
https://github.com/gavinlyonsrepo/pic_18F47K42_projects
https://github.com/gavinlyonsrepo/pic_16F18346_projects

regards

**Comment by Dave-10** [comment]
Hi Gavin,

Thanks for the feedback. I hope you didn't mind the suggestion. You are my first interaction on Github and I found your project most instructive.

Best regards,
Dave.

________________________________

**Comment by Dave-10** [comment]
Thanks, I'll have a look at the full library once I progress the project. Currently working with a PIC16F1459 and used the MCC interrupt driven I2C code along with your lightweight version of the library.
